#include <iostream>
#include <array>
#include <algorithm>
#include <unordered_set>
#include <unordered_map>
#include <vector>
#include <tuple>
#include <stack>
#include <queue>
#include <functional>